#!/bin/bash
echo "🚀 CODEMAGIC QUICK-START"
echo ""
echo "1. Öffne: https://codemagic.io/app"
echo "2. Klicke 'Add application'"
echo "3. Wähle GitHub Repository: funatiker1968-hub/Profi_Lotto_Neu"
echo "4. Wähle Workflow: lotto-app-android"
echo "5. Klicke 'Start first build'"
echo ""
echo "📊 ERWARTETER ABLAUF:"
echo "   ✅ Flutter Analyze (ca. 30s)"
echo "   ✅ Flutter Tests (ca. 20s)" 
echo "   ✅ APK Build (ca. 3-5min)"
echo "   ✅ AppBundle Build (ca. 1min)"
echo "   ✅ Artifacts Download verfügbar"
echo ""
echo "🎉 NACH ERFOLGREICHEM BUILD:"
echo "   - APK herunterladen"
echo "   - Auf Samsung S6 Lite testen"
echo "   - Bei Erfolg: Google Play einrichten (optional)"
